#!ruby

platform :ios, '7.0'

#Before push use:
#pod "SHUColorPicker"

#For local development use:
pod "SHUColorPicker", :path => "../SHUColorPicker.podspec"

link_with ['SHUColorPickerExample', 'SHUColorPickerExampleTests']
